apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vote
  name: vote-service
  namespace: vote
spec:
  ports:
    - nodePort: 31000
      port: 5000
      protocol: TCP
      targetPort: 80
  selector:
    app: vote
  type: NodePort
status:
  loadBalancer: {}